In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from itertools import combinations
from scipy.stats import ttest_ind


log = pd.read_csv('log.csv')

log.head().isna() 
log=log.rename(columns={'Запись пользователя № - user_919':'user_id','[2019-01-01 14:06:51':'time','Unnamed: 2':'bet','Unnamed: 3':'win'})
log.columns
log.head().isna() 

user_id   time    bet   win
0    False  False   True  True
1    False  False   True  True
2    False  False   True  True
3    False  False   True  True
4    False  False  False  True

In [7]:
log.time.isna().sum()

15

In [8]:
log1=log.rename(columns={'Запись пользователя № - user_919':'user_id','[2019-01-01 14:06:51':'time','Unnamed: 2':'bet','Unnamed: 3':'win'})

In [9]:
log1

user_id                  time       bet      win
0    Запись пользователя № - user_973  [2019-01-01 14:51:16       NaN      NaN
1    Запись пользователя № - user_903  [2019-01-01 16:31:16       NaN      NaN
2    Запись пользователя № - user_954  [2019-01-01 17:17:51       NaN      NaN
3    Запись пользователя № - user_954  [2019-01-01 21:31:18       NaN      NaN
4    Запись пользователя № - user_917  [2019-01-01 23:34:55  156789.0      NaN
..                                ...                   ...       ...      ...
994  Запись пользователя № - user_984   [2019-04-20 9:59:58    9754.0      NaN
995                            #error                   NaN   10054.0  29265.0
996                            #error                   NaN   10454.0      NaN
997                            #error                   NaN    1000.0      NaN
998                            #error                   NaN   10754.0      NaN

[999 rows x 4 columns]

In [10]:
log1.dropna(axis=0)

user_id                  time        bet  \
13   Запись пользователя № - user_917   [2019-01-02 8:57:36   145732.0   
28   Запись пользователя № - user_942  [2019-01-04 13:59:42  1678321.0   
150  Запись пользователя № - user_982  [2019-01-16 21:54:22      100.0   
188  Запись пользователя № - user_964  [2019-01-21 18:34:44      200.0   
204  Запись пользователя № - user_931   [2019-01-22 5:26:59      300.0   
..                                ...                   ...        ...   
966  Запись пользователя № - user_975  [2019-04-19 22:25:15     1000.0   
970  Запись пользователя № - user_912  [2019-04-20 10:35:49    10554.0   
971  Запись пользователя № - user_926  [2019-04-20 10:35:50    10354.0   
975  Запись пользователя № - user_970  [2019-04-20 10:35:54    10354.0   
990  Запись пользователя № - user_965  [2019-04-20 12:55:41      800.0   

           win  
13   1987653.0  
28   9876543.0  
150     4749.0  
188     4667.0  
204     4319.0  
..         ...  
966     6108.0  
970    31799.0  
971    30244.0  
975    30691.0  
990     6927.0  

[133 rows x 4 columns]

In [11]:
log.dropna(subset=['user_id','time'])

user_id                  time       bet     win
0    Запись пользователя № - user_973  [2019-01-01 14:51:16       NaN     NaN
1    Запись пользователя № - user_903  [2019-01-01 16:31:16       NaN     NaN
2    Запись пользователя № - user_954  [2019-01-01 17:17:51       NaN     NaN
3    Запись пользователя № - user_954  [2019-01-01 21:31:18       NaN     NaN
4    Запись пользователя № - user_917  [2019-01-01 23:34:55  156789.0     NaN
..                                ...                   ...       ...     ...
990  Запись пользователя № - user_965  [2019-04-20 12:55:41     800.0  6927.0
991  Запись пользователя № - user_967  [2019-04-20 14:59:36   10154.0     NaN
992  Запись пользователя № - user_973  [2019-04-20 17:09:56   10254.0     NaN
993  Запись пользователя № - user_977  [2019-04-20 18:10:07   10354.0     NaN
994  Запись пользователя № - user_984   [2019-04-20 9:59:58    9754.0     NaN

[984 rows x 4 columns]

In [12]:
import pandas as pd  
df = pd.read_csv('log.csv')
df.drop_duplicates()

Запись пользователя № - user_919  [2019-01-01 14:06:51  Unnamed: 2  \
0    Запись пользователя № - user_973  [2019-01-01 14:51:16         NaN   
1    Запись пользователя № - user_903  [2019-01-01 16:31:16         NaN   
2    Запись пользователя № - user_954  [2019-01-01 17:17:51         NaN   
3    Запись пользователя № - user_954  [2019-01-01 21:31:18         NaN   
4    Запись пользователя № - user_917  [2019-01-01 23:34:55    156789.0   
..                                ...                   ...         ...   
993  Запись пользователя № - user_977  [2019-04-20 18:10:07     10354.0   
994  Запись пользователя № - user_984   [2019-04-20 9:59:58      9754.0   
995                            #error                   NaN     10054.0   
996                            #error                   NaN     10454.0   
998                            #error                   NaN     10754.0   

     Unnamed: 3  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN  
..          ...  
993         NaN  
994         NaN  
995     29265.0  
996         NaN  
998         NaN  

[996 rows x 4 columns]

In [13]:
df=df.rename(columns={'Запись пользователя № - user_919':'user_id','[2019-01-01 14:06:51':'time','Unnamed: 2':'bet','Unnamed: 3':'win'})

In [14]:
df.drop_duplicates(['user_id','time'])

user_id                  time       bet     win
0    Запись пользователя № - user_973  [2019-01-01 14:51:16       NaN     NaN
1    Запись пользователя № - user_903  [2019-01-01 16:31:16       NaN     NaN
2    Запись пользователя № - user_954  [2019-01-01 17:17:51       NaN     NaN
3    Запись пользователя № - user_954  [2019-01-01 21:31:18       NaN     NaN
4    Запись пользователя № - user_917  [2019-01-01 23:34:55  156789.0     NaN
..                                ...                   ...       ...     ...
990  Запись пользователя № - user_965  [2019-04-20 12:55:41     800.0  6927.0
991  Запись пользователя № - user_967  [2019-04-20 14:59:36   10154.0     NaN
992  Запись пользователя № - user_973  [2019-04-20 17:09:56   10254.0     NaN
993  Запись пользователя № - user_977  [2019-04-20 18:10:07   10354.0     NaN
994  Запись пользователя № - user_984   [2019-04-20 9:59:58    9754.0     NaN

[985 rows x 4 columns]

In [15]:
log = pd.read_csv("log.csv")  
log = log.dropna()  
log.columns = ['user_id', 'time', 'bet', 'win']  
log['time'] = log['time'].apply(lambda x: x[1:])  
log['time'] = pd.to_datetime(log['time'])  
log3=log['time'].apply(lambda x: x.dayofweek==6)

log3.value_counts() 

False    112
True      21
Name: time, dtype: int64

In [16]:
log = pd.read_csv("log.csv")  

log.columns = ['user_id', 'time', 'bet', 'win']  

log4=log['bet'].fillna(0) 
log4.value_counts() 

0.0          514
500.0         50
100.0         48
300.0         42
800.0         42
200.0         40
400.0         40
700.0         38
600.0         37
1000.0        37
900.0         30
9754.0        10
10554.0       10
10154.0        7
10254.0        7
10454.0        6
9954.0         6
10754.0        5
10654.0        5
10354.0        4
10054.0        4
9854.0         2
5000.0         1
27000.0        1
9876.0         1
156789.0       1
12945.0        1
12548.0        1
145732.0       1
1678321.0      1
98753.0        1
123981.0       1
104540.0       1
8700.0         1
950.0          1
8734.0         1
7650.0         1
Name: bet, dtype: int64

In [17]:
import pandas as pd
from datetime import datetime
log = pd.read_csv('log.csv', header=None)
log.columns = ['user_id', 'time', 'bet', 'win']
log.bet=log['bet'].fillna(0)
log.win=log['win'].fillna(0)
def fillna_win(row):
    if row[3] == 0:
        if row[2] != 0:
            row[3] = row[3] - row[2]
    return row[3]
new_win = log.apply(lambda row: fillna_win(row), axis=1)  
log['win'] = new_win
log['net'] = log['win'] - log['bet']

In [18]:
log = pd.read_csv('log.csv', header=None)
log.columns=['user_id', 'time', 'bet', 'win']
log.bet=log['bet'].fillna(0)
log.win=log['win'].fillna(0)
log['net']=log['win']-log['bet']
# получаем датафрейм, где у нас была ставка
log555 = log[log['bet'] > 0]
# получаем из датафрейма со ставкой среднее по win, где был выигрыш,
# аналогично
# log[(log['bet'] > 0) & (log['net'] > 0)]['net'].mean()
log555[log555['net']>0]['net'].mean()
log555['net'].count()/log['bet'].count()

0.485

In [19]:
log = pd.read_csv('log.csv', header=None)
log.columns=['user_id', 'time', 'bet', 'win']
log.bet=log['bet'].fillna(0)
log.win=log['win'].fillna(0)
log['net']=log['win']-log['bet']
# получаем датафрейм, где у нас была ставка
log555 = log[log['bet'] > 0]
# получаем из датафрейма со ставкой среднее по win, где был выигрыш,
# аналогично
# log[(log['bet'] > 0) & (log['net'] > 0)]['net'].mean()
log[log['net']>0]['bet'].mean()


15367.688405797102

In [20]:
import numpy as np
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])
share_living_space = apartment[1]/apartment[0]
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)
print(share_living_space)

0.5277310924369748


In [21]:
len(apartment)

5

In [22]:
a=np.array([3, 4, 5, 9])
b=np.array([1, 5, 3, 6])
b*400-a*200

array([-200, 1200,  200,  600])

In [23]:
a=np.array([4, 5, -1])
b=np.array([2, 0, 1])
np.dot(a,b)

7

In [24]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [26]:
x = Hut_Paradise_DF.values # возвращает значения s
print('vector:\n',x)
print('type of x:',type(x))

vector:
 [[ 65  50   3   5   8  37]
 [ 70  52   2  12   4  40]
 [120  80   1  10   5  65]
 [ 35  33   1   3  10  20]
 [ 40  33   1   6  20  16]
 [ 50  44   2  13  12  35]
 [100  80   4   8   5  60]
 [ 90  65   3  21   1  50]
 [ 85  65   2   5  10  40]]
type of x: <class 'numpy.ndarray'>


In [27]:
df = pd.DataFrame(Hut_Paradise_DF)
print('Data Frame:\n',df)

Data Frame:
    1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40


In [29]:
A = df.values # возвращает значения df
print('Matrix:\n',A)

Matrix:
 [[ 65  50   3   5   8  37]
 [ 70  52   2  12   4  40]
 [120  80   1  10   5  65]
 [ 35  33   1   3  10  20]
 [ 40  33   1   6  20  16]
 [ 50  44   2  13  12  35]
 [100  80   4   8   5  60]
 [ 90  65   3  21   1  50]
 [ 85  65   2   5  10  40]]


In [30]:
x=A[4] # вторая строка матрицы А
print('Second apartment vector:\n',x)
print('type of x:',type(x))

Second apartment vector:
 [40 33  1  6 20 16]
type of x: <class 'numpy.ndarray'>


In [35]:
y=A[:,3] # вторая строка матрицы А
print('Second apartment vector:\n',y)
print('type of y:',type(y))

Second apartment vector:
 [ 5 12 10  3  6 13  8 21  5]
type of y: <class 'numpy.ndarray'>


In [37]:
print(A[:,3][2])

10


In [38]:
print(len(A))

9


In [39]:
print(A[:,1]-A[:,5])

[13 12 15 13 17  9 20 15 25]


In [40]:
print(A[:,0]*0.4)


[26. 28. 48. 14. 16. 20. 40. 36. 34.]


In [41]:
time=np.array([10,20,30,15,5,40,20,8,20])

print(Hut_Paradise_DF.iloc[:,4]@time)

1348


In [42]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [43]:
c=2*v-3*w
print(c)

[-3 14  3  4  2]


In [44]:
u_norm = u / np.linalg.norm(u)
v_norm = v / np.linalg.norm(v)
w_norm = w / np.linalg.norm(w)
print(u_norm[2])
print(v_norm[3])
print(w_norm[0])

0.2886751345948129
0.6666666666666666
0.21320071635561041


In [45]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [46]:
Inc=np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T

print(Inc[0,0], Inc[1,1], Inc[2,2])

100 200 100


In [47]:
Cons=np.array([Husband_Сonsumption,Wife_Сonsumption,Mother_In_Law_Сonsumption]).T

print(Cons[0,2], Cons[1,1], Cons[2,0])

100 80 60


In [48]:
Inc_Tax=Inc*(1-0.13)

print(Inc_Tax[0])



[ 87.  130.5  78.3]


In [49]:
Р=Inc_Tax-Cons

print(Р[2])

[ 61.8 -26.9 -53. ]


In [50]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [51]:
print(A@x)

[26 30]


In [52]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [53]:
C=B@A

print(C[0,3])

14


In [54]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [55]:
A = np.array([x, y, z]).T

print(A.T@A)

[[22  3  0]
 [ 3  7  0]
 [ 0  0  3]]


In [56]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [57]:
C = Count_DF.values

P = Price_DF.values

Boris_inc = C[1]*P[1]

print(Boris_inc)

[ 3.6 52.5  3.  25.   6. ]


In [58]:
salon_inc = (P*C)@(com)

print(salon_inc)

NameError: name 'com' is not defined

In [60]:
A=np.matrix("1,2;2,5")
np.linalg.inv(A)

matrix([[ 5., -2.],
        [-2.,  1.]])

In [61]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [62]:
A_inv = np.linalg.inv(A)

print(A_inv[1,0])

0.375


In [63]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [64]:
A = np.array([v1,v2,v3,v4])

np.linalg.matrix_rank(A)

4

In [65]:
Gram = A@A.T

print(Gram[0,3])

-35


In [66]:
det = np.linalg.det(Gram)

print(det)

3716647.9999999995


In [67]:
Gram_inv = np.linalg.inv(Gram)

print(Gram_inv[2,0])

-0.026230625014798288


In [2]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы DataFrame 
import seaborn as sns # библиотека для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

%matplotlib inline

In [3]:
AdmDF=pd.read_csv('Admission_Predict_Ver1.1.csv')

np.shape(AdmDF)[0]

500

In [4]:
AdmDF

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [6]:
Data=AdmDF[['GRE Score','TOEFL Score','University Rating','SOP','LOR','CGPA','Research','Chance of Admit']]
Data.head()

KeyError: "['Chance of Admit', 'LOR'] not in index"

In [7]:
data = pd.read_csv('data_flats.csv',sep=";")
data.head()

id  full_sq  life_sq  floor           sub_area  preschool_quota  \
0   1       43     27.0    4.0           Bibirevo           5001.0   
1   2       34     19.0    3.0  Nagatinskij Zaton           3119.0   
2   3       43     29.0    2.0     Tekstil'shhiki           1463.0   
3   4       89     50.0    9.0             Mitino           6839.0   
4   5       77     77.0    4.0          Basmannoe           3240.0   

   preschool_education_centers_raion  school_quota  \
0                                  5       11065.0   
1                                  5        6237.0   
2                                  4        5580.0   
3                                  9       17063.0   
4                                  7        7770.0   

   school_education_centers_raion  school_education_centers_top_20_raion  ...  \
0                               5                                      0  ...   
1                               8                                      0  ...   
2                               7                                      0  ...   
3                              10                                      0  ...   
4                               9                                      0  ...   

   shopping_centers_km  office_km  additional_education_km  preschool_km  \
0             0.648488   0.637189                 0.947962      0.177975   
1             0.519311   0.688796                 1.072315      0.273345   
2             1.486533   1.543049                 0.391957      0.158072   
3             0.599914   0.934273                 0.892674      0.236455   
4             0.429052   0.077901                 0.810801      0.376838   

   big_church_km  church_synagogue_km  theater_km  museum_km    ecology  \
0       0.625783             0.628187   14.053047   7.389498       good   
1       0.967821             0.471447    6.829889   0.709260  excellent   
2       3.178751             0.755946    4.273200   3.156423       poor   
3       1.031777             1.561505   16.990677  16.041521       good   
4       0.378756             0.121681    1.112486   1.800125  excellent   

   price_doc  
0    5850000  
1    6000000  
2    5700000  
3   13100000  
4   16331452  

[5 rows x 56 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30469 entries, 0 to 30468
Data columns (total 56 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id                                     30469 non-null  int64  
 1   full_sq                                30469 non-null  int64  
 2   life_sq                                24086 non-null  float64
 3   floor                                  30302 non-null  float64
 4   sub_area                               30469 non-null  object 
 5   preschool_quota                        23781 non-null  float64
 6   preschool_education_centers_raion      30469 non-null  int64  
 7   school_quota                           23784 non-null  float64
 8   school_education_centers_raion         30469 non-null  int64  
 9   school_education_centers_top_20_raion  30469 non-null  int64  
 10  hospital_beds_raion                    16029 non-null  float64
 11  he